paths:
  /free-movies:
    get:
      description: get free movies
      operationId: getFreeMovies
      responses:
        "200":
          $ref: '#/responses/FreeMovie'
      summary: get free movies
      tags:
      - movies
    post:
      description: add free movies
      operationId: addFreeMovies
      responses:
        "200":
          $ref: '#/responses/FreeMovie'
      summary: add free movies addFreeMovies
      tags:
      - movies
swagger: "2.0"
