host: localhost:8080
info:
  description: |-
    The purpose of this service is to provide an application
    that is using plain go code to define an API
  title: agfun API.
  version: 0.0.1
paths: {}
schemes:
- http
- https
swagger: "2.0"
