definitions:
  User:
    description: User represents the user for this application
    properties:
      access_token:
        type: string
        x-go-name: AccessToken
      create_time:
        format: date-time
        type: string
        x-go-name: CreateTime
      id:
        type: string
        x-go-name: ID
      nick_name:
        type: string
        x-go-name: NickName
      pwd:
        type: string
        x-go-name: Pwd
      role_id:
        format: uint64
        type: integer
        x-go-name: RoleID
      user_name:
        type: string
        x-go-name: UserName
      we_chat:
        type: string
        x-go-name: WeChat
    type: object
    x-go-package: agfun/auth/entity
host: localhost:8080
info:
  description: |-
    The purpose of this service is to provide an application
    that is using plain go code to define an API
  title: Auth API.
  version: 0.0.1
paths:
  /users/login/{user-name}:
    get:
      description: user login
      operationId: login
      parameters:
      - description: UserName
        in: path
        name: user-name
        required: true
        type: string
        x-go-name: UserName
      - description: Pwd
        in: query
        name: pwd
        type: string
        x-go-name: Pwd
      responses:
        "200":
          description: User
          schema:
            $ref: '#/definitions/User'
        "422":
          $ref: '#/responses/validationError'
        default:
          $ref: '#/responses/genericError'
      summary: user login
      tags:
      - users
  /users/register:
    post:
      description: this will register user account
      operationId: createUser
      parameters:
      - description: Created user object
        in: body
        name: body
        schema:
          $ref: '#/definitions/User'
        x-go-name: Body
      responses:
        "200":
          description: User
          schema:
            $ref: '#/definitions/User'
        "422":
          $ref: '#/responses/validationError'
        default:
          $ref: '#/responses/genericError'
      summary: register user account
      tags:
      - users
  /users/roles:
    post:
      description: add role
      operationId: addRole
      responses:
        "200":
          $ref: '#/responses/Role'
      summary: add role
      tags:
      - roles
responses:
  genericError:
    description: genericError
  validationError:
    description: validationError
schemes:
- http
- https
swagger: "2.0"
