export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAILURE = 'MOVIE_LIST_FAILURE'

export const MOVIE_POST_REQUEST = 'MOVIE_POST_REQUEST'
export const MOVIE_POST_SUCCESS = 'MOVIE_POST_SUCCESS'
export const MOVIE_POST_FAILURE = 'MOVIE_POST_FAILURE'
